apiVersion: v1
kind: Pod
metadata:
   name: redis
spec:
  containers:
   - image: redis
     name: redisdb
     volumeMounts:
        - name: redis-data
          mountPath: /data
     ports:
       - containerPort: 6379
         protocol: TCP
   - image: rediscommander/redis-commander
     name: rediscommander
     env:
       - name: REDIS_HOSTS
         value: localhost:6379
     ports:
       - name: redis-commander
         containerPort: 8081
  volumes:
    - name: redis-data
      persistentVolumeClaim:
          claimName: redis-pv-claim