apiVersion: v1
kind: Service
metadata:
  namespace: development
  name: mongodb-service
spec:
  selector:
    app: mongo-express
  ports:
    - name: mongoservice
      protocol: TCP
      port: 27017
      targetPort: 27017
    
    - name: mongoexpressservice
      protocol: TCP
      port: 8081
      targetPort: 8081
  
  
  type: LoadBalancer
  
    
