apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: development
  name: mongo-and-express-deployment
  labels:
    app: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
     containers:
      - name: mongodb
        image: mongo
        ports: 
          - containerPort: 27017
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongodb-secrets
                key: mongo-root-username
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongodb-secrets
                key: mongo-root-password 


      - name: express
        image: mongo-express
        ports:
          - containerPort: 8081
        env:
          - name: ME_CONFIG_MONGODB_ADMINUSERNAME
            valueFrom: 
             secretKeyRef: 
               name: mongodb-secrets
               key: mongo-root-username
          - name: ME_CONFIG_MONGODB_ADMINPASSWORD
            valueFrom:
              secretKeyRef:
                name: mongodb-secrets
                key: mongo-root-password
          - name: ME_CONFIG_MONGODB_SERVER
            value: localhost
